/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope;

/* 
 * FIREBASE MESSAGING & WORKBOX INTEGRATION
 * 
 * Firebase's default documentation assumes a dedicated `firebase-messaging-sw.js` file 
 * mapped to the root scope. However, because vite-plugin-pwa also needs to generate 
 * its own service worker for Workbox precaching, registering two separate, competing 
 * service workers at the exact same root scope will cause severe lifecycle collisions 
 * and unregistration loops.
 * 
 * Instead, we use vite-plugin-pwa's `injectManifest` strategy. This allows us to use 
 * a single custom service worker (this file) that natively imports Workbox to precache 
 * the static app shell, AND simultaneously imports/initializes firebase-messaging-compat 
 * to securely handle background push delivery within the exact same unified scope.
 */

// 1. Precache the static app shell generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// 2. Initialize Firebase for background push notifications
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID
};

const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

// 3. Handle background messages
onBackgroundMessage(messaging, (payload) => {
  console.log('[Service Worker] Received background message: ', payload);

  // If the payload contains a 'notification' object, Firebase's SDK automatically 
  // displays a system notification for us. If it is a data-only payload, we would 
  // construct and show the notification manually here using self.registration.showNotification.
});
