import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  server: {
    host: true,
    port: 5174,
    allowedHosts: true,
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
      '/ws': {
        target: 'ws://127.0.0.1:8000',
        ws: true,
        changeOrigin: true,
      },
    },
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true,
      },
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'icons/*.png'],
      manifest: {
        name: 'CrowdShield Citizen Safety',
        short_name: 'CrowdShield',
        id: '/',
        scope: '/',
        start_url: '/',
        display: 'fullscreen',
        display_override: ['fullscreen', 'standalone', 'window-controls-overlay'],
        orientation: 'portrait',
        prefer_related_applications: false,
        theme_color: '#0f172a',
        background_color: '#0f172a',
        icons: [
          {
            src: '/icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png'
            // TODO: Swap these placeholder icons for real artwork before the pitch
          },
          {
            src: '/icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          },
          {
            src: '/icons/icon-512x512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable'
          }
        ]
      },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        // Cache ONLY static build assets natively generated by Vite.
        globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
        
        // EXPLICITLY EXCLUDE /api/* and WebSocket upgrades from caching.
        // Live risk data MUST NEVER be served stale from a service-worker cache.
        // Note: For injectManifest, navigateFallbackDenylist does not apply the same way unless manually handled in SW,
        // but it's safe to keep or simply let Workbox precaching handle the globs.
      }
    })
  ],
})
