import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'icons/*.png'],
      manifest: {
        name: 'CrowdShield Citizen Safety',
        short_name: 'CrowdShield',
        start_url: '/',
        display: 'standalone',
        theme_color: '#0f172a',
        background_color: '#0f172a',
        icons: [
          {
            src: '/icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png'
            // TODO: Swap these placeholder icons for real artwork before the pitch
          },
          {
            src: '/icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          },
          {
            src: '/icons/icon-512x512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable'
          }
        ]
      },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        // Cache ONLY static build assets natively generated by Vite.
        globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
        
        // EXPLICITLY EXCLUDE /api/* and WebSocket upgrades from caching.
        // Live risk data MUST NEVER be served stale from a service-worker cache.
        // Note: For injectManifest, navigateFallbackDenylist does not apply the same way unless manually handled in SW,
        // but it's safe to keep or simply let Workbox precaching handle the globs.
      }
    })
  ],
})
